services:
  - type: web
    name: scamresolvedcsi
    env: python
    plan: free
    autoDeploy: true
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: WEB_CONCURRENCY
        value: "2"
      - key: DEBUG
        value: "False"

