services:
  - type: web
    name: scamresolvedcsi
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application
    postDeployCommand: python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py seed_blog
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DJANGO_ALLOWED_HOSTS
        value: *.onrender.com
      - key: SECRET_KEY
        generateValue: true
      - key: CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com
      - key: WEB_CONCURRENCY
        value: "2"
      - key: DEBUG
        value: "False"

